name: Manual
on:
 workflow_dispatch:
  inputs:
   greeting:
    type: string
    default: Hello
    required: true
    descrition: A cheeful word
  jobs:
   run:
    runs-on: ubuntu-latest
    steps:
     - run: echo"${{inputs.greeting}}"